services:
  postgres:
    image: postgres:16
    container_name: messageboard-db
    environment:
      POSTGRES_USER: itsmeharry
      POSTGRES_PASSWORD: thisisnotastandardpasswordanditsactuallyreallylongsoihopeyouseeitprofessor
      POSTGRES_DB: itsthedatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    image: messageboard-web:local
    container_name: messageboard-web
    depends_on:
      - postgres
    environment:
      - CONNECTIONSTRING=Host=postgres;Port=5432;Database=itsthedatabase;Username=itsmeharry;Password=thisisnotastandardpasswordanditsactuallyreallylongsoihopeyouseeitprofessor
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag
    container_name: harry_swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=harryclass.duckdns.org
      - VALIDATION=dns
      - DNSPLUGIN=duckdns
      - PROPAGATION=420
    volumes:
      - ./swag:/config
      - ./nginx-config.conf:/config/nginx/site-confs/default.conf
    ports:
      - 3000:443
    restart: unless-stopped

volumes:
  postgres_data:
