apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: harry-ingress
spec:
  rules:
  - host: 100.96.241.36
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: fast-api
            port:
              number: 3003